[package]
name = "novus-userland"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[lib]
name = "novus_userland"
path = "src/lib.rs"
test = false
doctest = false
bench = false

[[bin]]
name = "hello_world"
path = "src/bin/hello_world.rs"
test = false
doctest = false
bench = false

[[bin]]
name = "add"
path = "src/bin/add.rs"
test = false
doctest = false
bench = false
