[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-Cforce-frame-pointers=yes"
 ]

runner = "./scripts/start.sh --blk ./resources/minix.qcow2 --kernel"
