[package]
name = "athera-userland"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[lib]
name = "athera_userland"
path = "src/lib.rs"
test = false
doctest = false
bench = false

[[bin]]
name = "init"
path = "src/bin/init.rs"
test = false
doctest = false
bench = false

[[bin]]
name = "hello_world"
path = "src/bin/hello_world.rs"
test = false
doctest = false
bench = false

[[bin]]
name = "add"
path = "src/bin/add.rs"
test = false
doctest = false
bench = false

[[bin]]
name = "sort"
path = "src/bin/sort.rs"
test = false
doctest = false
bench = false

[[bin]]
name = "panic"
path = "src/bin/panic.rs"
test = false
doctest = false
bench = false

[[bin]]
name = "quick_sort"
path = "src/bin/quick_sort.rs"
test = false
doctest = false
bench = false

[[bin]]
name = "fork"
path = "src/bin/fork.rs"
test = false
doctest = false
bench = false

[[bin]]
name = "heap"
path = "src/bin/heap.rs"
test = false
doctest = false
bench = false

[[bin]]
name = "conway"
path = "src/bin/conway.rs"
test = false
doctest = false
bench = false

[[bin]]
name = "print_args"
path = "src/bin/print_args.rs"
test = false
doctest = false
bench = false

[[bin]]
name = "mmap_test"
path = "src/bin/mmap_test.rs"
test = false
doctest = false
bench = false

